const STELLAR_CLI_VERSION = "26.1.0";
const SOROBAN_SDK_VERSION = "27.0.3";

const contracts = [
  {
    package: "recursive-delegate-account-contract",
    wasm: "recursive_delegate_account_contract.wasm",
    spec: "recursive-delegate-account.ts",
    exportName: "RECURSIVE_DELEGATE_ACCOUNT_SPEC",
  },
  {
    package: "delegated-asset-account-contract",
    wasm: "delegated_asset_account_contract.wasm",
    spec: "delegated-asset-account.ts",
    exportName: "DELEGATED_ASSET_ACCOUNT_SPEC",
  },
] as const;

const check = Deno.args.includes("--check");
const contractsDirectory = new URL("./", import.meta.url);
const artifactDirectory = new URL("artifacts/", contractsDirectory);
const specDirectory = new URL("specs/", contractsDirectory);
const manifestUrl = new URL("artifacts.sha256.json", artifactDirectory);

async function command(executable: string, args: string[]): Promise<string> {
  const output = await new Deno.Command(executable, {
    args,
    cwd: contractsDirectory,
    stdout: "piped",
    stderr: "inherit",
  }).output();
  if (!output.success) {
    throw new Error(`${executable} ${args.join(" ")} failed`);
  }
  return new TextDecoder().decode(output.stdout).trim();
}

async function assertPinnedToolchain(): Promise<void> {
  const stellarVersion = await command("stellar", ["--version"]);
  if (!stellarVersion.includes(`stellar ${STELLAR_CLI_VERSION}`)) {
    throw new Error(
      `Expected Stellar CLI ${STELLAR_CLI_VERSION}, got ${stellarVersion}`,
    );
  }
  const manifest = await Deno.readTextFile(
    new URL("Cargo.toml", contractsDirectory),
  );
  if (!manifest.includes(`soroban-sdk = "=${SOROBAN_SDK_VERSION}"`)) {
    throw new Error(`Expected soroban-sdk ${SOROBAN_SDK_VERSION}`);
  }
}

async function sha256(value: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", Uint8Array.from(value));
  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

function specSource(exportName: string, entries: string[]): string {
  return [
    "// Generated by contracts/build.ts. Do not edit.",
    'import { Spec } from "stellar-sdk/contract";',
    "",
    `export const ${exportName} = new Spec([`,
    ...entries.map((entry) => `  ${JSON.stringify(entry)},`),
    "]);",
    "",
  ].join("\n");
}

async function sameFile(url: URL, expected: Uint8Array): Promise<boolean> {
  try {
    const actual = await Deno.readFile(url);
    return actual.length === expected.length &&
      actual.every((byte, index) => byte === expected[index]);
  } catch (cause) {
    if (cause instanceof Deno.errors.NotFound) return false;
    throw cause;
  }
}

await assertPinnedToolchain();
const buildDirectory = await Deno.makeTempDir({
  prefix: "colibri-signer-example-",
});
const hashes: Record<string, string> = {};
const stale: string[] = [];

try {
  for (const contract of contracts) {
    await command("stellar", [
      "contract",
      "build",
      "--locked",
      "--manifest-path",
      new URL("Cargo.toml", contractsDirectory).pathname,
      "--package",
      contract.package,
      "--out-dir",
      buildDirectory,
    ]);
    const builtUrl = new URL(
      contract.wasm,
      `file://${buildDirectory.replace(/\/?$/, "/")}`,
    );
    const wasm = await Deno.readFile(builtUrl);
    const specEntries = JSON.parse(
      await command("stellar", [
        "contract",
        "inspect",
        "--wasm",
        builtUrl.pathname,
        "--output",
        "xdr-base64-array",
      ]),
    ) as string[];
    const spec = new TextEncoder().encode(
      specSource(contract.exportName, specEntries),
    );
    const artifactUrl = new URL(contract.wasm, artifactDirectory);
    const specUrl = new URL(contract.spec, specDirectory);
    hashes[contract.wasm] = await sha256(wasm);

    if (check) {
      if (!(await sameFile(artifactUrl, wasm))) stale.push(contract.wasm);
      if (!(await sameFile(specUrl, spec))) stale.push(contract.spec);
    } else {
      await Deno.mkdir(artifactDirectory, { recursive: true });
      await Deno.mkdir(specDirectory, { recursive: true });
      await Deno.writeFile(artifactUrl, wasm);
      await Deno.writeFile(specUrl, spec);
    }
  }

  const manifest = new TextEncoder().encode(
    `${
      JSON.stringify(
        {
          stellarCli: STELLAR_CLI_VERSION,
          sorobanSdk: SOROBAN_SDK_VERSION,
          artifacts: hashes,
        },
        null,
        2,
      )
    }\n`,
  );
  if (check) {
    if (!(await sameFile(manifestUrl, manifest))) {
      stale.push("artifacts.sha256.json");
    }
    if (stale.length > 0) {
      throw new Error(`Stale signer example artifacts: ${stale.join(", ")}`);
    }
  } else {
    await Deno.writeFile(manifestUrl, manifest);
  }
} finally {
  await Deno.remove(buildDirectory, { recursive: true });
}
