/**
 * Example: Optional Contract Artifact Build
 *
 * Rebuild the lesson's Wasm and SDK specifications together, or compare them
 * with the checked-in artifacts using --check. Normal consumers use the
 * included fixtures and do not invoke this helper.
 *
 * Run: deno task contract:build
 */
const SOROBAN_SDK_VERSION = "27.0.3";

const contracts = [
  {
    package: "recursive-delegate-account-contract",
    wasm: "recursive_delegate_account_contract.wasm",
    spec: "recursive-delegate-account.ts",
    exportName: "RECURSIVE_DELEGATE_ACCOUNT_SPEC",
  },
  {
    package: "delegated-asset-account-contract",
    wasm: "delegated_asset_account_contract.wasm",
    spec: "delegated-asset-account.ts",
    exportName: "DELEGATED_ASSET_ACCOUNT_SPEC",
  },
] as const;

const check = Deno.args.includes("--check");
const contractsDirectory = new URL("./", import.meta.url);
const artifactDirectory = new URL("artifacts/", contractsDirectory);
const specDirectory = new URL("specs/", contractsDirectory);
const manifestUrl = new URL("artifacts.sha256.json", artifactDirectory);

/**
 * Run a tool in the contract source directory and stop on a nonzero exit.
 * Inheriting stderr keeps compiler diagnostics visible while stdout captures
 * the extracted specification for the generated module.
 */
async function command(executable: string, args: string[]): Promise<string> {
  const output = await new Deno.Command(executable, {
    args,
    cwd: contractsDirectory,
    stdout: "piped",
    stderr: "inherit",
  }).output();

  if (!output.success) {
    throw new Error(`${executable} ${args.join(" ")} failed`);
  }

  return new TextDecoder().decode(output.stdout).trim();
}

/**
 * Check that the CLI supports interface extraction and that the manifest
 * still selects the fixture's expected Rust SDK. Exact artifact reproduction
 * also depends on the compiler and CLI used to build it.
 */
async function assertToolchain(): Promise<void> {
  await command("stellar", ["contract", "info", "interface", "--help"]);

  const manifest = await Deno.readTextFile(
    new URL("Cargo.toml", contractsDirectory),
  );

  if (!manifest.includes(`soroban-sdk = "=${SOROBAN_SDK_VERSION}"`)) {
    throw new Error(`Expected soroban-sdk ${SOROBAN_SDK_VERSION}`);
  }
}

async function sha256(value: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", Uint8Array.from(value));

  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

/**
 * Wrap the extracted base64 XDR stream in a native Stellar SDK Spec export.
 * These are support artifacts for the contract lesson, not handwritten
 * client bindings.
 */
function specSource(exportName: string, entryStream: string): string {
  return [
    "// Generated by contracts/build.ts. Do not edit.",
    'import { Spec } from "stellar-sdk/contract";',
    "",
    `export const ${exportName} = new Spec(`,
    `  ${JSON.stringify(entryStream)},`,
    ");",
    "",
  ].join("\n");
}

async function sameFile(url: URL, expected: Uint8Array): Promise<boolean> {
  try {
    const actual = await Deno.readFile(url);

    return actual.length === expected.length &&
      actual.every((byte, index) => byte === expected[index]);
  } catch (cause) {
    if (cause instanceof Deno.errors.NotFound) return false;

    throw cause;
  }
}

await assertToolchain();

const buildDirectory = await Deno.makeTempDir({
  prefix: "colibri-delegated-signers-",
});

const hashes: Record<string, string> = {};
const stale: string[] = [];

// Keep build output in a temporary directory and remove it even on failure.
try {
  for (const contract of contracts) {
    await command("stellar", [
      "contract",
      "build",
      "--locked",
      "--manifest-path",
      new URL("Cargo.toml", contractsDirectory).pathname,
      "--package",
      contract.package,
      "--out-dir",
      buildDirectory,
    ]);

    const builtUrl = new URL(
      contract.wasm,
      `file://${buildDirectory.replace(/\/?$/, "/")}`,
    );

    const wasm = await Deno.readFile(builtUrl);

    /**
     * Extract the specification from the newly built Wasm so executable code
     * and its ABI come from the same build. Check mode compares both outputs
     * without replacing committed artifacts.
     */
    const specEntries = await command("stellar", [
      "contract",
      "info",
      "interface",
      "--wasm",
      builtUrl.pathname,
      "--output",
      "xdr-base64",
    ]);

    const spec = new TextEncoder().encode(
      specSource(contract.exportName, specEntries),
    );
    const artifactUrl = new URL(contract.wasm, artifactDirectory);
    const specUrl = new URL(contract.spec, specDirectory);

    hashes[contract.wasm] = await sha256(wasm);

    // Check mode is read-only for checked-in artifacts. Normal mode updates them.
    if (check) {
      if (!(await sameFile(artifactUrl, wasm))) stale.push(contract.wasm);

      if (!(await sameFile(specUrl, spec))) stale.push(contract.spec);
    } else {
      await Deno.mkdir(artifactDirectory, { recursive: true });

      await Deno.mkdir(specDirectory, { recursive: true });

      await Deno.writeFile(artifactUrl, wasm);

      await Deno.writeFile(specUrl, spec);
    }
  }

  /**
   * Record the rebuilt Wasm hashes after processing every fixture. In check
   * mode, compare this record with the committed manifest as well as
   * comparing the actual Wasm and specification bytes.
   */
  const manifest = new TextEncoder().encode(
    `${
      JSON.stringify(
        {
          sorobanSdk: SOROBAN_SDK_VERSION,
          artifacts: hashes,
        },
        null,
        2,
      )
    }\n`,
  );

  if (check) {
    if (!(await sameFile(manifestUrl, manifest))) {
      stale.push("artifacts.sha256.json");
    }

    if (stale.length > 0) {
      throw new Error(
        `Stale delegated signer artifacts: ${stale.join(", ")}`,
      );
    }
  } else {
    await Deno.writeFile(manifestUrl, manifest);
  }
} finally {
  await Deno.remove(buildDirectory, { recursive: true });
}
