export const lessons = [
  {
    id: "network",
    group: "Start here",
    title: "Network & provider",
    subtitle: "One application. One Testnet connection.",
    file: "network/overview",
    hooks: ["useColibriConfig", "useNetwork", "useRpc", "useLatestLedger"],
  },
  {
    id: "ecosystem",
    group: "Start here",
    title: "The wallet ecosystem",
    subtitle: "Understand where the wallet ends and Colibri begins.",
    file: "wallets/ecosystem",
    hooks: [],
  },
  {
    id: "wallet",
    group: "Wallets & signing",
    title: "Connect a wallet",
    subtitle: "Wallets Kit selection, connection and disconnect.",
    file: "wallets/wallet",
    hooks: ["useWallet"],
  },
  {
    id: "connection",
    group: "Wallets & signing",
    title: "Connection primitives",
    subtitle: "Observe, connect, restore and release a connection.",
    file: "wallets/connection",
    hooks: ["useConnection", "useConnect", "useReconnect", "useDisconnect"],
  },
  {
    id: "freighter",
    group: "Wallets & signing",
    title: "Direct Freighter",
    subtitle: "An independent adapter for a single-wallet application.",
    file: "wallets/freighter",
    hooks: ["useConnect", "useConnection"],
  },
  {
    id: "signers",
    group: "Wallets & signing",
    title: "Signing capabilities",
    subtitle: "An account address is not signing authority.",
    file: "signing/signers",
    hooks: ["useSigners"],
  },
  {
    id: "message",
    group: "Wallets & signing",
    title: "Sign a message",
    subtitle: "A disposable identity and a real SEP-53 signature.",
    file: "signing/message",
    hooks: ["useSignMessage"],
  },
  {
    id: "account",
    group: "Accounts & assets",
    title: "Read an account",
    subtitle: "Read public account state directly from Stellar RPC.",
    file: "accounts/account",
    hooks: ["useAccount"],
  },
  {
    id: "trustline",
    group: "Accounts & assets",
    title: "Read a trustline",
    subtitle: "Inspect a Classic asset's balance, limit and flags.",
    file: "accounts/trustline",
    hooks: ["useTrustline"],
  },
  {
    id: "ledger-entries",
    group: "Accounts & assets",
    title: "Ledger entries",
    subtitle: "Compose a known-key read with Colibri's ledger reader.",
    file: "accounts/ledger-entries",
    hooks: ["useLedgerEntries"],
  },
  {
    id: "xlm",
    group: "Accounts & assets",
    title: "XLM balance",
    subtitle: "Display stroops as XLM without losing precision.",
    file: "assets/xlm",
    hooks: ["useBalance"],
  },
  {
    id: "classic-asset",
    group: "Accounts & assets",
    title: "Classic asset balance",
    subtitle: "Identify an issued asset by its code and issuer.",
    file: "assets/classic",
    hooks: ["useBalance"],
  },
  {
    id: "token",
    group: "Accounts & assets",
    title: "SEP-41 token balance",
    subtitle: "Read a contract balance with its declared precision.",
    file: "assets/token",
    hooks: ["useBalance", "useTokenMetadata"],
  },
  {
    id: "contract",
    group: "Contracts",
    title: "A full contract client",
    subtitle: "Keep a generated client's identity and pipelines stable.",
    file: "contracts/instance",
    hooks: ["useContract"],
  },
  {
    id: "contract-read",
    group: "Contracts",
    title: "Read through a client",
    subtitle: "A typed generated method, observed as a React query.",
    file: "contracts/read",
    hooks: ["useContractRead"],
  },
  {
    id: "spec-read",
    group: "Contracts",
    title: "Read with a spec",
    subtitle: "Call an ABI method without constructing a full client.",
    file: "contracts/spec-read",
    hooks: ["useContractReadSpec"],
  },
  {
    id: "contract-invoke",
    group: "Contracts",
    title: "Invoke with signers",
    subtitle: "Supply transaction authority explicitly and refresh the read.",
    file: "contracts/invoke",
    hooks: ["useContractInvoke"],
  },
  {
    id: "wallet-invoke",
    group: "Contracts",
    title: "Invoke with a wallet",
    subtitle: "Let the connected wallet supply source and signers.",
    file: "contracts/wallet-invoke",
    hooks: ["useWalletContractInvoke"],
  },
  {
    id: "payment",
    group: "Transactions",
    title: "Classic payment",
    subtitle: "Build and submit a native XLM payment.",
    file: "transactions/classic-payment",
    hooks: ["useClassicTransaction"],
  },
  {
    id: "simulate",
    group: "Transactions",
    title: "Simulate Soroban",
    subtitle: "Inspect a prepared transaction without signing or submitting.",
    file: "transactions/simulate",
    hooks: ["useSimulateSorobanTransaction"],
  },
  {
    id: "soroban",
    group: "Transactions",
    title: "Submit Soroban",
    subtitle: "Take a contract operation through the invocation pipeline.",
    file: "transactions/soroban",
    hooks: ["useSorobanTransaction"],
  },
  {
    id: "transaction",
    group: "Transactions",
    title: "Look up a transaction",
    subtitle: "Read a transaction hash and distinguish NOT_FOUND from failure.",
    file: "transactions/lookup",
    hooks: ["useTransaction"],
  },
  {
    id: "confirmation",
    group: "Transactions",
    title: "Wait for confirmation",
    subtitle: "Poll an existing hash, with an explicit stop control.",
    file: "transactions/confirmation",
    hooks: ["useWaitForTransaction"],
  },
  {
    id: "events",
    group: "Discovery & state",
    title: "Contract events",
    subtitle: "Observe a bounded event stream and clean up on navigation.",
    file: "events/events",
    hooks: ["useContractEvents"],
  },
  {
    id: "toml",
    group: "Discovery & state",
    title: "Discover stellar.toml",
    subtitle: "Read a domain's SEP-1 service declarations.",
    file: "discovery/toml",
    hooks: ["useStellarToml"],
  },
  {
    id: "identicon",
    group: "Discovery & state",
    title: "Account identicons",
    subtitle: "Render a deterministic identity locally.",
    file: "discovery/identicon",
    hooks: ["useIdenticon"],
  },
  {
    id: "query",
    group: "Discovery & state",
    title: "Compose an action",
    subtitle:
      "Use Colibri's mutation lifecycle for an application-owned action.",
    file: "queries/mutation",
    hooks: ["useColibriMutation"],
  },
  {
    id: "auth-client",
    group: "Authentication",
    title: "Discover WebAuth",
    subtitle: "Discover the local Testnet SEP-10 service.",
    file: "sessions/client",
    hooks: ["useWebAuthClient"],
  },
  {
    id: "session",
    group: "Authentication",
    title: "Authenticate & log out",
    subtitle: "Complete a real challenge exchange with a memory-only session.",
    file: "sessions/session",
    hooks: ["useWebAuth", "useSession"],
  },
] as const;
export type Lesson = typeof lessons[number];
