/**
 * Example: SEP-45 Deployment Setup
 *
 * Prepare the verification contract, custom account and localhost HTTP
 * fixture for sep45.ts. Authentication and the account-specific signing
 * callback remain visible in that consumer script.
 */
import {
  Contract,
  initializeWithFriendbot,
  LocalSigner,
  NativeAccount,
  NetworkConfig,
  type TransactionConfig,
} from "@colibri/core";
import { Keypair, rpc } from "stellar-sdk";
import { type LocalWebAuthServer, startLocalWebAuthServer } from "./server.ts";
import { PASSKEY_ACCOUNT_SPEC } from "./contracts/specs/passkey-account.ts";
import { WEB_AUTH_SPEC } from "./contracts/specs/web-auth.ts";

export interface TestnetWebAuthEnvironment {
  contractAccount: string;
  network: ReturnType<typeof NetworkConfig.TestNet>;
  server: LocalWebAuthServer;
  close(): Promise<void>;
}

async function wasm(name: string): Promise<Uint8Array> {
  return await Deno.readFile(
    new URL(`./contracts/artifacts/${name}`, import.meta.url),
  );
}

/**
 * Deploy the two contract roles and start the local server. publicKey is the
 * software P-256 credential generated by sep45.ts and installed in the
 * account constructor. Return the account address and connection details,
 * plus cleanup for the HTTP listener.
 */
export async function deployTestnetContracts(publicKey: Uint8Array): Promise<
  TestnetWebAuthEnvironment
> {
  let server: LocalWebAuthServer | undefined;

  try {
    const network = NetworkConfig.TestNet();
    const rpcServer = new rpc.Server(network.rpcUrl, {
      allowHttp: network.allowHttp,
    });

    /**
     * The admin pays and signs for deployment. The server uses a different
     * key to sign its own SEP-45 challenge requirement; neither role
     * replaces the client account's P-256 authorization.
     */
    const admin = NativeAccount.fromMasterSigner(LocalSigner.generateRandom());
    const serverSigner = Keypair.random();

    await initializeWithFriendbot(network.friendbotUrl, admin.address(), {
      rpcUrl: network.rpcUrl,
      allowHttp: network.allowHttp,
    });

    await initializeWithFriendbot(
      network.friendbotUrl,
      serverSigner.publicKey() as `G${string}`,
      {
        rpcUrl: network.rpcUrl,
        allowHttp: network.allowHttp,
      },
    );

    const transactionConfig: TransactionConfig = {
      source: admin.address(),
      fee: "10000000",
      timeout: 30,
      signers: [admin.signer()],
    };

    /**
     * The verification contract declares the account and server
     * authorization requirements. It is distinct from the custom account
     * contract deployed next, which decides how the client's signature is
     * checked.
     */
    const webAuthContract = new Contract({
      networkConfig: network,
      contractConfig: {
        wasm: await wasm("web_auth_contract.wasm"),
        spec: WEB_AUTH_SPEC,
      },
    });

    await webAuthContract.uploadWasm(transactionConfig);

    await webAuthContract.deploy({ config: transactionConfig });

    /**
     * Install the caller's public credential in a fresh custom account. Its
     * __check_auth implementation expects the WebAuthn-shaped assertion
     * assembled in sep45.ts.
     */
    const passkeyAccount = new Contract({
      networkConfig: network,
      contractConfig: {
        wasm: await wasm("passkey_account_contract.wasm"),
        spec: PASSKEY_ACCOUNT_SPEC,
      },
    });

    await passkeyAccount.uploadWasm(transactionConfig);

    await passkeyAccount.deploy({
      config: transactionConfig,
      constructorArgs: {
        public_key: publicKey,
      },
    });

    const contractAccount = passkeyAccount.getContractId();

    /**
     * Publish the discovery TOML and challenge endpoints on localhost after
     * both contract addresses exist. The returned cleanup function closes
     * this HTTP fixture; it does not remove the Testnet contracts.
     */
    server = startLocalWebAuthServer({
      networkPassphrase: network.networkPassphrase,
      rpc: rpcServer,
      webAuthContractId: webAuthContract.getContractId(),
      server: serverSigner,
    });

    return {
      contractAccount,
      network,
      server,
      async close() {
        await server?.close();
      },
    };
  } catch (cause) {
    await server?.close();

    throw cause;
  }
}
