/**
 * Stellar Testnet connection and funding helpers for delegated examples.
 *
 * Testnet provides the same protocol behavior needed to exercise delegated
 * authorization without putting real funds at risk. Friendbot creates and funds
 * the disposable identities generated by each script.
 */
import {
  initializeWithFriendbot,
  type LocalSigner,
  NetworkConfig,
} from "@colibri/core";
import { Server } from "stellar-sdk/rpc";

// `NetworkConfig.TestNet()` keeps the passphrase, RPC URL, Friendbot URL, and
// HTTP policy together so every Colibri component targets the same network.
export const networkConfig = NetworkConfig.TestNet();
export const rpc = new Server(networkConfig.rpcUrl, {
  allowHttp: networkConfig.allowHttp,
});

/**
 * Creates and funds each disposable identity through Friendbot, one at a time.
 *
 * The examples intentionally do not persist these secret keys. Re-running a
 * command therefore creates an independent demonstration topology.
 */
export async function fund(
  ...signers: LocalSigner[]
): Promise<void> {
  for (const signer of signers) {
    console.log(`   Funding ${signer.publicKey()}...`);
    await initializeWithFriendbot(
      networkConfig.friendbotUrl,
      signer.publicKey(),
      {
        rpcUrl: networkConfig.rpcUrl,
        allowHttp: networkConfig.allowHttp,
      },
    );
  }
}
